name: pocket_hisab_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.0

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/splash-screen-logo.svg
    - assets/logo.svg

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.svg"
